package dadiatre;

public class PlayerFrame extends javax.swing.JFrame {

    private final Lancio l;
    private final int id;
    
    public PlayerFrame(Lancio l, int id) {
        this.l = l;
        this.id = id;
        initComponents();
    }
    
    public void updateScores() {
        jl_score1.setText(Integer.toString(l.getPuntiG1()));
        jl_score2.setText(Integer.toString(l.getPuntiG2()));
        jl_score3.setText(Integer.toString(l.getPuntiG3()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jl_score1 = new javax.swing.JLabel();
        jl_score2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jl_score3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        playerHistory = new javax.swing.JTextArea();
        throwButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Giocatore 1");

        jl_score1.setText("jLabel2");

        jl_score2.setText("jLabel2");

        jLabel4.setText("Giocatore 2");

        jl_score3.setText("jLabel2");

        jLabel6.setText("Giocatore 3");

        playerHistory.setEditable(false);
        playerHistory.setColumns(20);
        playerHistory.setRows(5);
        jScrollPane1.setViewportView(playerHistory);

        throwButton.setText("Lancia!");
        throwButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                throwButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(116, 116, 116)
                                .addComponent(jl_score1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(116, 116, 116)
                                .addComponent(jl_score2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(116, 116, 116)
                                .addComponent(jl_score3)))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addComponent(throwButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jl_score1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jl_score2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jl_score3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(throwButton)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jl_score1.getAccessibleContext().setAccessibleName("jl_score1");
        jl_score2.getAccessibleContext().setAccessibleName("jl_score2");
        jl_score3.getAccessibleContext().setAccessibleName("jl_score3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void throwButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_throwButtonActionPerformed
        int res = l.LancioDado();
        l.setPunti(id, res);
        playerHistory.setText(playerHistory.getText() + Integer.toString(res) + "\n");
        updateScores();
    }//GEN-LAST:event_throwButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jl_score1;
    private javax.swing.JLabel jl_score2;
    private javax.swing.JLabel jl_score3;
    private javax.swing.JTextArea playerHistory;
    private javax.swing.JButton throwButton;
    // End of variables declaration//GEN-END:variables
}
